trigger:
  branches:
    include:
      - master
  paths:
    include:
      - azure-pipelines.sdk.yml

pool:
  vmImage: "ubuntu-latest"

variables:
  tag: "sdk:latest"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "tencentyun"
      command: "login"
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $env:tag="$(tag)"
        docker pull mcr.microsoft.com/dotnet/core/$env:tag
        docker tag mcr.microsoft.com/dotnet/core/$env:tag ccr.ccs.tencentyun.com/ye4241/$env:tag
        docker push ccr.ccs.tencentyun.com/ye4241/$env:tag
