trigger:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

variables:
  tag: "runtime:latest"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "tencentyun"
      command: "login"
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $env:aspnet="$(tag)"
        docker pull mcr.microsoft.com/dotnet/core/$env:tag
        docker tag mcr.microsoft.com/dotnet/core/$env:tag ccr.ccs.tencentyun.com/ye4241/$env:tag
        docker push ccr.ccs.tencentyun.com/ye4241/$env:tag
