trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: 'aspnet:latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'tencentyun'
    command: 'login'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $env:version="$(tag)"
      docker pull mcr.microsoft.com/dotnet/core/$env:version
      docker tag mcr.microsoft.com/dotnet/core/$env:version ccr.ccs.tencentyun.com/ye4241/$env:version
      docker push ccr.ccs.tencentyun.com/ye4241/$env:version
