trigger:
  branches:
    include:
      - master
  paths:
    include:
      - mssql/server.yml

pool:
  vmImage: "ubuntu-latest"

variables:
  tag: "mssql/server:2017-latest"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "tencentyun"
      command: "login"
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $source = "mcr.microsoft.com/$(tag)"
        $target = "ccr.ccs.tencentyun.com/ye4241/" + ("$(tag)" -replace "/",".")
        docker pull $source
        docker tag $source $target
        docker push $target
