trigger:
  branches:
    include:
      - master
  paths:
    include:
      - mssql/server.yml

pool:
  vmImage: "ubuntu-latest"

variables:
  tag: "mssql/server:2017-latest"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "tencentyun"
      command: "login"
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $source = "$(tag)"
        $target = "$(tag)" -replace "/","."
        docker pull "mcr.microsoft.com/$(source)"
        docker tag "mcr.microsoft.com/$(source)" "ccr.ccs.tencentyun.com/ye4241/$(target)"
        docker push "ccr.ccs.tencentyun.com/ye4241/$(target)"
