trigger: none

jobs:
  - template: ../templates/jobs.yml
    parameters:
      path: "mssql/server"
      tags:
        - key: "2017"
          value: "2017-latest"
        - key: "2019"
          value: "2019-latest"
        - key: "2017_CU20"
          value: "2017-CU20-ubuntu-16.04"
        - key: "2019_CU4"
          value: "2019-CU4-ubuntu-16.04"
