trigger:
  branches:
    include:
      - master
  paths:
    include:
      - dotnet/core/aspnet.yml

pool:
  name: "default"

variables:
  tag: "dotnet/core/aspnet:latest"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "tencentyun"
      command: "login"
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $source = "mcr.microsoft.com/$(tag)" 
        $target = "ccr.ccs.tencentyun.com/ye4241/" + ("$(tag)" -replace "/",".")

        echo pull from $source
        docker pull $source

        echo tag to $target
        docker tag $source $target

        echo push to $target
        docker push $target
