trigger:
  branches:
    include:
      - master
  paths:
    include:
      - dotnet/core/runtime.yml

variables:
  path: "dotnet/core/runtime"
  tags: ""

jobs:
  - template: ../../templates/jobs.yml
    parameters:
      path: $(path)
      tags:
        - "latest"
        - "3.1"
        - "2.1"
        - "5.0"
