trigger:
  branches:
    include:
      - master
  paths:
    include:
      - dotnet/core/runtime.yml

variables:
  path: "dotnet/core/runtime"
  tags: [latest", "3.1", "2.1", "5.0"]

jobs:
  - template: ../../templates/jobs.yml
    parameters:
      path: $(path)
      tags: $(tags)
