trigger: none

jobs:
  - template: ../../templates/jobs.yml
    parameters:
      path: "dotnet/core/sdk"
      tags:
        - key: "latest"
          value: "latest"
        - key: "3_1"
          value: "3.1"
        - key: "2_1"
          value: "2.1"
        - key: "5_0"
          value: "5.0"
